spring:
  security:
    user:
      name: Prabakaran
      password: narakabarp

  cloud:
    azure:
      key-vault:
        uri: ${AZURE_KEY_VAULT_URI:YOUR_KEY_VAULT_URI} # Azure Key Vault URI
      storage:
        connection-string: ${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING:YOUR_STORAGE_ACCOUNT_CONNECTION_STRING} # Azure Storage Account Connection String

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:5431/cloudapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000  # 30 seconds
      maximum-pool-size: 10

server:
  port: 9080
  servlet:
    context-path: /aps