package files.stash.domain.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * Represents a member entity in the system.
 * <p>
 * This entity stores information about an individual, such as personal details and department affiliation.
 */
@Getter
@Setter
public class Member {

    /**
     * Unique identifier for the member (typically auto-generated by the database).
     */
    private Long id;

    /**
     * Roll number or unique code assigned to the member (e.g., student ID or employee code).
     */
    private String rollNo;

    /**
     * First name of the member.
     */
    private String firstName;

    /**
     * Last name of the member.
     */
    private String lastName;

    /**
     * Full name of the member, typically a combination of first name and last name.
     */
    private String fullName;

    /**
     * Department to which the member belongs.
     */
    private Department department;

    /**
     * Email address of the member.
     */
    private String emailAddress;

    /**
     * Designation or job title of the member.
     */
    private String designation;

    /**
     * Phone number of the member.
     */
    private Long phoneNumber;
}
