spring:
  cloud:
    azure:
      key-vault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT:} # Endpoint URL to connect the Azure Key Vault
      storage:
        container-name: ${AZURE_STORAGE_CONTAINER_NAME:stashit}
        connection-string: ${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING:} # Azure Storage Account Connection String

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/stashit} # JDBC url to connect database
    username: ${DATASOURCE_USERNAME:postgres} # Database username
    password: ${DATASOURCE_PASSWORD:password} # Database password
    hikari:
      connection-timeout: 30000  # 30 seconds
      maximum-pool-size: 10

server:
  port: ${SERVER_PORT:9080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/aps}

# Logging configuration
logging:
  level:
    files.stash: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"