name: Build and deploy JAR app to Azure Web App - files-vault-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Grant execute permissions for Gradle Wrapper
      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew

      # Build with Gradle (with stacktrace for more detailed errors)
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # Debugging: List files in build/ directory
      - name: List files in build directory after build
        run: ls -alh ${GITHUB_WORKSPACE}/build

      # Debugging: List files in build/libs directory
      - name: List files in build/libs directory after build
        run: ls -alh ${GITHUB_WORKSPACE}/build/libs

      # Upload artifact for deployment job (only if the JAR is present)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build job completes
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Debugging: List downloaded files to ensure the artifact is available
      - name: List downloaded files (Debugging step)
        run: ls -alh ${{ github.workspace }}/java-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBAA0B4F8CB64AFB91D5D470E171E71B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F0B677099F846F788E5E90FCAC51589 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54B137CAA492463EB72BB22B57BC5FD5 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'files-vault-app'
          slot-name: 'Production'
          package: './java-app/*.jar'
