name: Build and deploy JAR app to Azure Web App - files-vault-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Grant execute permissions for Gradle Wrapper
      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew

      # Build with Gradle from the correct subdirectory
      - name: Build with Gradle
        working-directory: Sub-Cloud-App
        run: ./gradlew build --stacktrace

      # Debugging: List files in build/libs directory
      - name: List files in Sub-Cloud-App build/libs directory after build
        run: ls -alh ${GITHUB_WORKSPACE}/Sub-Cloud-App/build/libs

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Sub-Cloud-App/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/java-app

      # Debugging: List downloaded files to ensure the artifact is available
      - name: List downloaded files (Debugging step)
        run: ls -alh ${{ github.workspace }}/java-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F3A7946F19A4760B58F9E98BC3D5E99 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F0B677099F846F788E5E90FCAC51589 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00C16A0D58AE462E9AC002292FBA59C8 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'files-vault'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/*.jar'
