name: Build and deploy JAR app to Azure Web App - files-vault-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Step 3: Grant execute permissions for Gradle Wrapper
      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew

      # Step 4: Build the project with Gradle (with stacktrace for debugging)
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # Step 5: List files in the project directory (Debugging step)
      - name: List files in the project directory (Debugging step)
        run: ls -alh ${GITHUB_WORKSPACE}

      # Step 6: List build/libs directory (if it exists)
      - name: List build/libs directory (Debugging step)
        run: ls -alh ${GITHUB_WORKSPACE}/build/libs || echo "No build/libs directory found"

      # Step 7: Upload the artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Step 2: Debugging step to list files in the downloaded artifact folder
      - name: List downloaded files (Debugging step)
        run: ls -alh ${{ github.workspace }}/java-app

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBAA0B4F8CB64AFB91D5D470E171E71B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F0B677099F846F788E5E90FCAC51589 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54B137CAA492463EB72BB22B57BC5FD5 }}

      # Step 4: Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'files-vault-app'
          slot-name: 'Production'
          package: './java-app/*.jar'  # Ensure the correct path for the downloaded artifact
